name: Deploy Java File with AzCopy

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        required: true
        default: 'myproject'
        options:
          - 'myproject'
          - 'anotherproject'

jobs:
  deploy:
    name: Deploy Java File
    runs-on: windows-latest
    environment: dev
    env:
      AZCOPY_SPA_APPLICATION_ID: ${{ secrets.CLIENTID }}
      AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      AZCOPY_TENANT_ID: ${{ secrets.TENANTID }}
      AZCOPY_AUTO_LOGIN_TYPE: SPN
      AZURE_DESTINATION_PATH: ${{ secrets.STORAGE_ACCOUNT_URL }}/path/to/destination/

    steps:
      # Step 1: Check out the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Build the Java file
      - name: Build Project
        run: mvn package -DskipTests

      # Step 4: Verify artifact is built
          
      - name: Verify Artifact
        run: |
          dir target\*.jar
        shell: cmd



      # Step 5: Install AzCopy
      - name: Install AzCopy
        run: |
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile AzCopy.zip
          Expand-Archive -Path AzCopy.zip -DestinationPath AzCopy
          echo "AzCopy installed."

      # Step 6: Deploy using AzCopy
      - name: Deploy with AzCopy
        run: |
          AzCopy\azcopy.exe copy "target/*.jar" "${{ env.AZURE_DESTINATION_PATH }}" --recursive
        shell: cmd
