name: Maven-Deploy-Workflow

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        required: true
        default: 'cds'
        options:
          - 'cds'
          - 'content'
          - 'media'
          - 'fuelight'
          - 'wklypls'
          - 'gmp'

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    environment: dev
    env:
      AZCOPY_SPA_APPLICATION_ID: ${{ secrets.CLIENTID }}
      AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      AZCOPY_TENANT_ID: ${{ secrets.TENANTID }}
      AZCOPY_AUTO_LOGIN_TYPE: SPN
      MAVEN_OPTS: "-Xss4M"
      DEV_FILE_PATH: ${{ secrets.STORAGE_ACCOUNT_URL }}/cokefs/github-files
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8.0
        uses: actions/setup-java@v3
        with:
          java-version: '8.0'
          distribution: 'temurin'
          cache: maven

      - name: Generate settings.xml
        run: |
          cat <<EOF > ./settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.MAVEN_USERNAME }}</username>
                <password>${{ secrets.MAVEN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Maven Package
        run: mvn -B package --file pom.xml -s ./settings.xml -P TCCC-snapshot-feed -DskipTests

      - name: Debug Artifact Location
        run: ls -al target

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifact
          path: target/*.jar

  move-jar-file:
    name: Move Jar File
    runs-on: self-hosted
    needs: build
    environment: dev
    env:
      AZCOPY_SPA_APPLICATION_ID: ${{ secrets.CLIENTID }}
      AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      AZCOPY_TENANT_ID: ${{ secrets.TENANTID }}
      AZCOPY_AUTO_LOGIN_TYPE: SPN
      DEV_FILE_PATH: ${{ github.event.inputs.project == 'content' && vars.DEV_DAM_JAR_FILE_PATH || 
        github.event.inputs.project == 'cds' && vars.DEV_CDS_JAR_FILE_PATH || 
        github.event.inputs.project == 'media' && vars.DEV_MEDIA_JAR_FILE_PATH ||
        github.event.inputs.project == 'fuelight' && vars.DEV_FUELIGHT_JAR_FILE_PATH ||
        github.event.inputs.project == 'wklypls' && vars.DEV_WKLYPLS_JAR_FILE_PATH ||
        github.event.inputs.project == 'gmp' && vars.DEV_GMP_JAR_FILE_PATH ||
        vars.DEV_CDS_JAR_FILE_PATH }}
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-artifact
          path: target

      - name: Install AzCopy
        run: |
          # Download AzCopy from Microsoft
          Invoke-WebRequest -Uri https://aka.ms/downloadazcopy-v10-windows -OutFile "AzCopy.zip"
          
          # Extract AzCopy to the "AzCopy" directory
          Expand-Archive -Path AzCopy.zip -DestinationPath AzCopy

          # Add AzCopy to the PATH
          $env:PATH += ";${PWD}\AzCopy"

      # Step to check if AzCopy is installed and in the path
      #- name: Verify AzCopy Installation
       # run: |
         # Get-Command AzCopy.exe | Select-Object Source
       # shell: pwsh

      # Run AzCopy with the full path
      - name: Run AzCopy with azcopy.exe
        run: |
         echo "Source: target/*.jar"
         echo "Destination: ${{ env.DEV_FILE_PATH }}"
        
         & "C:\Windows\System32\actions-runner\_work\othergit\othergit\AzCopy\azcopy_windows_amd64_10.27.1\azcopy.exe" copy "C:\Windows\System32\actions-runner\_work\your-repo-name\your-repo-name\target\*.jar" "${{ env.DEV_FILE_PATH }}" --recursive --from-to LocalBlob
      - name: Debug AzCopy Command
        run: |
          echo "C:\Windows\System32\actions-runner\_work\othergit\othergit\AzCopy\azcopy_windows_amd64_10.27.1\azcopy.exe copy 'target/*.jar' '${{ env.DEV_FILE_PATH }}' --recursive"
